analyzer/urls.py
from django.urls import path

from . import views
from analyzer.features import HAS_TASK_MERGE

app_name = 'analyzer'

urlpatterns = [
    path('', views.list_lists,  name="lists"),

    # View reorder_tasks is only called by JQuery for drag/drop task ordering.
    path('reorder_tasks/', views.reorder_tasks, name="reorder_tasks"),

    # Three paths into `list_detail` view
    path('mine/', views.list_detail, {'list_slug': 'mine'}, name="mine"),

    path('<int:list_id>/<str:list_slug>/checked/', views.list_detail, {'view_checked': True},
         name='list_detail_checked'),
    path('<int:list_id>/<str:list_slug>/', views.list_detail, name='list_detail'),
    path('<int:list_id>/<str:list_slug>/delete/', views.del_list, name="del_list"),

    path('add_list/', views.add_list, name="add_list"),
    path('task/<str:task_id>/', views.task_detail, name='task_detail'),
    path('attachment/remove/<int:attachment_id>/', views.remove_attachment, name='remove_attachment'),
    path('attachment/predict/<int:attachment_id>/', views.prediction, name='prediction'),
]

if HAS_TASK_MERGE:
    # ensure mail tracker autocomplete is optional
    from analyzer.views.task_autocomplete import TaskAutocomplete
    urlpatterns.append(path('task/<str:task_id>/autocomplete/', TaskAutocomplete.as_view(), name='task_autocomplete'))

urlpatterns.extend([
    path('toggle_done/<str:task_id>/', views.toggle_done, name='task_toggle_done'),
    path('delete/<str:task_id>/', views.delete_task, name='delete_task'),
    path('search/', views.search, name="search"),
    path('import_csv/', views.import_csv, name="import_csv"),
])

authz/urls.py
from django.urls import path
from . import views
from django.views.generic import TemplateView

app_name='authz'
urlpatterns = [
    path('', TemplateView.as_view(template_name='authz/main.html')),
    path('open', views.OpenView.as_view(), name='open'),
    path('apereo', views.ApereoView.as_view(), name='apereo'),
    path('manual', views.ManualProtect.as_view(), name='manual'),
    path('protect', views.ProtectView.as_view(), name='protect'),
    path('python', views.DumpPython.as_view(), name='python'),
]

sentimento/urls.py
import os

from django.contrib import admin
from django.urls import include, path
from django.views.generic import TemplateView
from django.views.static import serve
from django.conf.urls.static import static
from django.conf import settings

# Up two folders to serve "site" content
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

urlpatterns = [
    path('admin/', admin.site.urls),

    # Sample applications
    path('', TemplateView.as_view(template_name='home/main.html'), name='home_page'),
    path('authz/', include('authz.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('analyzer/', include('analyzer.urls', namespace='analyzer')),
]

# Serve the favicon
urlpatterns += [
    path('favicon.ico', serve, {
        'path': 'favicon.ico',
        'document_root': os.path.join(BASE_DIR, 'home/static'),
    }),
]

# Serve the media
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

home/templates/home/base.html
{% load static %}
{% load app_tags %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="Sentimento Web">
    <meta name="author" content="JackShen">

    <title>Sentimento Web App</title>
    <link rel="icon" href="{% static 'home/ico/logo.ico' %}" type="image/x-icon">

    <!-- Bootstrap core CSS -->
    <link rel='stylesheet' href='https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css'>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/css/bootstrap.min.css" integrity="sha384-B0vP5xmATw1+K9KRQjQERJvTumQW0nPEzvF6L/Z6nronJ3oUOFUFpCjEUQouq2+l" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/normalize/5.0.0/normalize.min.css">
    <link href="{% static 'analyzer/css/style.css' %}" rel="stylesheet">

    <!-- Custom styles for this template -->
    <style>
        body { background-image: url('{% static "analyzer/img/main-wallpaper.jpg" %}'); }
    </style>

    {# Additional CSS or html head data inserted by templates here. #}
    {% block extrahead %}{% endblock extrahead %}
</head>

<body>


<div class="app">

    <div class="header">
        <div class="header-menu">
            {% if user.is_authenticated %}
                <a class="menu-link" href="{% url 'logout' %}">Log Out</a>
            {% else %}
                <a class="menu-link" href="{% url 'login' %}">Log In</a>
            {% endif %}
        </div>

         <div class="header-profile">
             {% if user.is_authenticated %}
                 {{ user.username }}
                 <img class="profile-img" src="{{ user|gravatar:60 }}" alt="avatar"/>
             {% endif %}
             <i id="default-version" style="color: var(--theme-color); font-size: 1.5rem; display: none; margin-left: 40px; cursor: pointer;" class="fa fa-undo"></i>
         </div>

    </div>

    <div class="wrapper">
        <div class="main-container">
            <div class="content-wrapper">
                <div class="content-section">
                    {% if messages %}
                        {% for message in messages %}
                            <div class="alert {% if message.tags %}alert-{% if message.tags == 'error' %}danger{% else %}{{ message.tags }}{% endif %}{% endif %}">{{ message }}</div>
                        {% endfor %}
                    {% endif %}

                    {% if form.errors %}
                        <p>{{ form.non_field_errors }}</p>
                    {% endif %}

                    {% block content %}{% endblock %}
                </div>
            </div>
        </div>
    </div>
</div>

<span class="content-section-footer-title">Sentimento Web, {% now "Y" %}</span>
<!-- jQuery and Bootstrap core JS, plus Popper -->
<script src="https://code.jquery.com/jquery-3.5.1.js" integrity="sha256-QWo7LDvxbWT2tbbQ97B53yJnYU3WhH/C8ycbRAkjPDc=" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/js/bootstrap.min.js" integrity="sha384-+YQ4JLhjyBLPDQt//I+STsc9iw4uQqACwlvpslubQzn4u2UU2UFM80nGisd026JF" crossorigin="anonymous"></script>

<script src="{% static 'analyzer/js/script.js' %}"></script>
{% block extra_js %} {% endblock extra_js %}
</body>
</html>

home/templates/home/main.html
{% extends "home/base.html" %}

{% block extrahead %}
    <style>
        form { display: inline-block; }
    </style>
{% endblock %}


{% block content %}
    <h1 style="text-align: center;">Welcome to Sentimento Web!</h1>

    <p>
        On this site you can add recommendation and motivation letters, and the administrator can conduct their sentiment analysis and share with you the result.
        <br><br>
        After filling out the forms, a unique link will be formed for you, and you will be able to follow the news about your document analysis.
        <br><br>
        Click the button below to add documents 🙃
    </p>

    <span style="text-align: center;">
        {# Here place a link to the page where you want the user to add documents #}
        <form style="text-align: center;" action="../analyzer/1/motivation-lists/">
            <input type="submit" class="btn btn-primary mt-4" style="width: 180px;" value="Add Documents" />
        </form>

        {% if user.is_authenticated %}
        <form style="text-align: center;" action="{% url 'analyzer:lists' %}">
            <input type="submit" class="btn btn-success mt-4" style="width: 180px;" value="Analyzer Stats" />
        </form>
        {% endif %}
    </span>
{% endblock %}