authz/urls.py
from django.urls import path
from . import views
from django.views.generic import TemplateView

app_name='authz'
urlpatterns = [
    path('', TemplateView.as_view(template_name='authz/main.html')),
    path('open', views.OpenView.as_view(), name='open'),
    path('apereo', views.ApereoView.as_view(), name='apereo'),
    path('manual', views.ManualProtect.as_view(), name='manual'),
    path('protect', views.ProtectView.as_view(), name='protect'),
    path('python', views.DumpPython.as_view(), name='python'),
]

sentimento/urls.py
import os

from django.contrib import admin
from django.urls import include, path
from django.views.generic import TemplateView
from django.views.static import serve
from django.conf.urls.static import static
from django.conf import settings

# Up two folders to serve "site" content
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

urlpatterns = [
    path('admin/', admin.site.urls),

    # Sample applications
    path('', TemplateView.as_view(template_name='home/main.html'), name='home_page'),
    path('authz/', include('authz.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('analyzer/', include('analyzer.urls', namespace='analyzer')),
]

# Serve the favicon
urlpatterns += [
    path('favicon.ico', serve, {
        'path': 'favicon.ico',
        'document_root': os.path.join(BASE_DIR, 'home/static'),
    }),
]

# Serve the media
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

authz/models.py
from django.db import models

# Create your models here.

authz/views.py
from django.shortcuts import render, redirect
from django.views import View
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse
from django.utils.http import urlencode

class OpenView(View) :
    def get(self, request):
        return render(request, 'authz/main.html')

class ApereoView(View) :
    def get(self, request):
        return render(request, 'authz/main.html')

class ManualProtect(View) :
    def get(self, request):
        if not request.user.is_authenticated :
            loginurl = reverse('login')+'?'+urlencode({'next': request.path})
            return redirect(loginurl)
        return render(request, 'authz/main.html')

class ProtectView(LoginRequiredMixin, View) :
    def get(self, request):
        return render(request, 'authz/main.html')

from django.http import HttpResponse

class DumpPython(View) :
    def get(self, req):
        resp = "<pre>\nUser Data in Python:\n\n"
        resp += "Login url: " + reverse('login') + "\n"
        resp += "Logout url: " + reverse('logout') + "\n\n"
        if req.user.is_authenticated:
            resp += "User: " + req.user.username + "\n"
            resp += "Email: " + req.user.email + "\n"
        else:
            resp += "User is not logged in\n"

        resp += "\n"
        resp += "</pre>\n"
        resp += """<a href="/authz">Go back</a>"""
        return HttpResponse(resp)


# https://docs.djangoproject.com/en/3.0/topics/auth/default/#authentication-in-web-requests

authz/templates/authz/main.html
<h1>Current request.path {{ request.path }}</h1>
{% if user.is_authenticated %}
<p>Authenticated as
<pre>
Name: {{ user.get_full_name }}
Email: {{ user.email }}
Id: {{ user.id }}
</pre>
</p>
<p>You can <a href="{% url 'logout' %}?next={% url 'authz:open' %}">Logout</a></p>
{% else %}
<p>You are not logged in</p>
<p>You can <a href="{% url 'login' %}?next={{ request.path }}">Login</a> if you like.</p>
{% endif %}
<ul>
    <li>
        Go to <a href="{% url 'authz:open' %}">{% url 'authz:open' %}</a>
            (no login required)
    </li>
    <li>
        Go to <a href="{% url 'authz:apereo' %}">{% url 'authz:apereo' %}</a>
            (no login required)
    </li>
    <li>
        Go to <a href="{% url 'authz:manual' %}">{% url 'authz:manual' %}</a>
            (protected by user.is_authenticated)
    </li>
    <li>
        Go to <a href="{% url 'authz:protect' %}">{% url 'authz:protect' %}</a>
            (protected by LoginRequiredMixin)
    </li>
    <li>
        Go to <a href="{% url 'authz:python' %}">{% url 'authz:python' %}</a>
            dump request.user data in python
    </li>
</ul>