analyzer/urls.py
from django.urls import path

from . import views
from analyzer.features import HAS_TASK_MERGE

app_name = 'analyzer'

urlpatterns = [
    path('', views.list_lists,  name="lists"),

    # View reorder_tasks is only called by JQuery for drag/drop task ordering.
    path('reorder_tasks/', views.reorder_tasks, name="reorder_tasks"),

    # Three paths into `list_detail` view
    path('mine/', views.list_detail, {'list_slug': 'mine'}, name="mine"),

    path('<int:list_id>/<str:list_slug>/checked/', views.list_detail, {'view_checked': True},
         name='list_detail_checked'),
    path('<int:list_id>/<str:list_slug>/', views.list_detail, name='list_detail'),
    path('<int:list_id>/<str:list_slug>/delete/', views.del_list, name="del_list"),

    path('add_list/', views.add_list, name="add_list"),
    path('task/<str:task_id>/', views.task_detail, name='task_detail'),
    path('attachment/remove/<int:attachment_id>/', views.remove_attachment, name='remove_attachment'),
    path('attachment/predict/<int:attachment_id>/', views.prediction, name='prediction'),
]

if HAS_TASK_MERGE:
    # ensure mail tracker autocomplete is optional
    from analyzer.views.task_autocomplete import TaskAutocomplete
    urlpatterns.append(path('task/<str:task_id>/autocomplete/', TaskAutocomplete.as_view(), name='task_autocomplete'))

urlpatterns.extend([
    path('toggle_done/<str:task_id>/', views.toggle_done, name='task_toggle_done'),
    path('delete/<str:task_id>/', views.delete_task, name='delete_task'),
    path('search/', views.search, name="search"),
    path('import_csv/', views.import_csv, name="import_csv"),
])

authz/urls.py
from django.urls import path
from . import views
from django.views.generic import TemplateView

app_name='authz'
urlpatterns = [
    path('', TemplateView.as_view(template_name='authz/main.html')),
    path('open', views.OpenView.as_view(), name='open'),
    path('apereo', views.ApereoView.as_view(), name='apereo'),
    path('manual', views.ManualProtect.as_view(), name='manual'),
    path('protect', views.ProtectView.as_view(), name='protect'),
    path('python', views.DumpPython.as_view(), name='python'),
]

sentimento/urls.py
import os

from django.contrib import admin
from django.urls import include, path
from django.views.generic import TemplateView
from django.views.static import serve
from django.conf.urls.static import static
from django.conf import settings

# Up two folders to serve "site" content
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

urlpatterns = [
    path('admin/', admin.site.urls),

    # Sample applications
    path('', TemplateView.as_view(template_name='home/main.html'), name='home_page'),
    path('authz/', include('authz.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('analyzer/', include('analyzer.urls', namespace='analyzer')),
]

# Serve the favicon
urlpatterns += [
    path('favicon.ico', serve, {
        'path': 'favicon.ico',
        'document_root': os.path.join(BASE_DIR, 'home/static'),
    }),
]

# Serve the media
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

analyzer/models.py
from __future__ import unicode_literals

import datetime
import os
import textwrap
import uuid

from django.conf import settings
from django.contrib.auth.models import Group
from django.db import DEFAULT_DB_ALIAS, models
from django.db.transaction import Atomic, get_connection
from django.urls import reverse
from django.utils import timezone


def get_attachment_upload_dir(instance, filename):
    """Determine upload dir for task attachment files."""
    return "/".join(["tasks", "attachments", str(instance.task.id), filename])


class LockedAtomicTransaction(Atomic):
    """
    This is needed for safely merging

    Does a atomic transaction, but also locks the entire table for any transactions, for the duration of this
    transaction. Although this is the only way to avoid concurrency issues in certain situations, it should be used with
    caution, since it has impacts on performance, for obvious reasons...
    """

    def __init__(self, *models, using=None, savepoint=None):
        if using is None:
            using = DEFAULT_DB_ALIAS
        super().__init__(using, savepoint)
        self.models = models

    def __enter__(self):
        super(LockedAtomicTransaction, self).__enter__()

        # Make sure not to lock, when sqlite is used, or you'll run into problems while running tests!!!
        if settings.DATABASES[self.using]["ENGINE"] != "django.db.backends.sqlite3":
            cursor = None
            try:
                cursor = get_connection(self.using).cursor()
                for model in self.models:
                    cursor.execute("LOCK TABLE {table_name}".format(table_name=model._meta.db_table))
            finally:
                if cursor and not cursor.closed:
                    cursor.close()


class TaskList(models.Model):
    name = models.CharField(max_length=60)
    slug = models.SlugField(default="")
    group = models.ForeignKey(Group, on_delete=models.CASCADE)

    def __str__(self):
        return self.name

    class Meta:
        ordering = ["name"]
        verbose_name_plural = "Task Lists"

        # Prevents (at the database level) creation of two lists with the same slug in the same group
        unique_together = ("group", "slug")


class Task(models.Model):
    id = models.CharField(max_length=100, blank=True, unique=True, primary_key=True, default=uuid.uuid4)
    username = models.CharField(max_length=140)
    task_list = models.ForeignKey(TaskList, on_delete=models.CASCADE, null=True)
    created_date = models.DateField(default=timezone.now, blank=True, null=True)
    email = models.CharField(max_length=100, blank=False, default=False)
    checked = models.BooleanField(default=False)
    checked_date = models.DateField(blank=True, null=True)
    assigned_to = models.ForeignKey(settings.AUTH_USER_MODEL, blank=True, null=True, related_name="task_assigned_to",
                                    on_delete=models.CASCADE, )
    note = models.TextField(blank=True, null=True)
    priority = models.PositiveIntegerField(blank=True, null=True)

    def __str__(self):
        return self.username

    def get_absolute_url(self):
        return reverse("analyzer:task_detail", kwargs={"task_id": self.id})

    # Auto-set the Task creation / checked date
    def save(self, **kwargs):
        # If Task is being marked complete, set the checked_date
        if self.checked:
            self.checked_date = datetime.datetime.now()
        super(Task, self).save()

    def merge_into(self, merge_target):
        if merge_target.pk == self.pk:
            raise ValueError("can't merge a task with self")

        # lock the comments to avoid concurrent additions of comments after the
        # update request. these comments would be irremediably lost because of
        # the cascade clause
        with LockedAtomicTransaction(Comment):
            Comment.objects.filter(task=self).update(task=merge_target)
            self.delete()

    class Meta:
        ordering = ["priority", "created_date"]


class Comment(models.Model):
    """
    Not using Django's built-in comments because we want to be able to save
    a comment and change task details at the same time. Rolling our own since it's easy.
    """

    task = models.ForeignKey(Task, on_delete=models.CASCADE)
    author = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, blank=True, null=True)
    date = models.DateTimeField(default=datetime.datetime.now)

    body = models.TextField(blank=True)

    @property
    def author_text(self):
        if self.author is not None:
            return str(self.author)

    @property
    def snippet(self):
        body_snippet = textwrap.shorten(self.body, width=35, placeholder="...")
        # Define here rather than in __str__ so we can use it in the admin list_display
        return "{author} - {snippet}...".format(author=self.author_text, snippet=body_snippet)

    def __str__(self):
        return self.snippet


class Attachment(models.Model):
    """ Defines a generic file attachment for use in M2M relation with Task """

    task = models.ForeignKey(Task, on_delete=models.CASCADE)
    timestamp = models.DateTimeField(default=datetime.datetime.now)
    file = models.FileField(upload_to=get_attachment_upload_dir, max_length=255)

    def filename(self):
        return os.path.basename(self.file.name)

    def extension(self):
        name, extension = os.path.splitext(self.file.name)
        return extension

    def __str__(self):
        return f"{self.task.id} - {self.file.name}"

analyzer/views/add_list.py
from django.contrib import messages
from django.contrib.auth.decorators import login_required, user_passes_test
from django.core.exceptions import PermissionDenied
from django.db import IntegrityError
from django.http import HttpResponse
from django.shortcuts import redirect, render
from django.utils.text import slugify

from analyzer.forms import AddTaskListForm
from analyzer.utils import staff_check


@login_required
@user_passes_test(staff_check)
def add_list(request) -> HttpResponse:
    """Allow users to add a new list to the group they're in."""

    # Only staffers can add lists, regardless of STAFF_USER setting.
    if not request.user.is_staff:
        raise PermissionDenied

    if request.POST:
        form = AddTaskListForm(request.user, request.POST)
        if form.is_valid():
            try:
                newlist = form.save(commit=False)
                newlist.slug = slugify(newlist.name, allow_unicode=True)
                newlist.save()
                messages.success(request, "A new list has been added.")
                return redirect("analyzer:lists")

            except IntegrityError:
                messages.warning(request, "There was a problem saving the new list. "
                                          "Most likely a list with the same name in the same group already exists.", )
    else:
        if request.user.groups.all().count() == 1:
            form = AddTaskListForm(request.user, initial={"group": request.user.groups.all()[0]})
        else:
            form = AddTaskListForm(request.user)

    context = {"form": form}

    return render(request, "analyzer/add_list.html", context)

analyzer/views/del_list.py
from django.contrib import messages
from django.contrib.auth.decorators import login_required, user_passes_test
from django.core.exceptions import PermissionDenied
from django.http import HttpResponse
from django.shortcuts import get_object_or_404, redirect, render

from analyzer.models import Task, TaskList
from analyzer.utils import staff_check


@login_required
@user_passes_test(staff_check)
def del_list(request, list_id: int, list_slug: str) -> HttpResponse:
    """Delete an entire list. Only staff members should be allowed to access this view."""
    task_list = get_object_or_404(TaskList, id=list_id)

    # Ensure user has permission to delete list. Get the group this list belongs to,
    # and check whether current user is a member of that group AND a staffer.
    if task_list.group not in request.user.groups.all():
        raise PermissionDenied
    if not request.user.is_staff:
        raise PermissionDenied

    if request.method == "POST":
        TaskList.objects.get(id=task_list.id).delete()
        messages.success(request, "{list_name} is gone.".format(list_name=task_list.name))
        return redirect("analyzer:lists")
    else:
        task_count_done = Task.objects.filter(task_list=task_list.id, checked=True).count()
        task_count_undone = Task.objects.filter(task_list=task_list.id, checked=False).count()
        task_count_total = Task.objects.filter(task_list=task_list.id).count()

    context = {
        "task_list": task_list,
        "task_count_done": task_count_done,
        "task_count_undone": task_count_undone,
        "task_count_total": task_count_total,
    }

    return render(request, "analyzer/del_list.html", context)

analyzer/views/delete_task.py
from django.contrib import messages
from django.contrib.auth.decorators import login_required, user_passes_test
from django.core.exceptions import PermissionDenied
from django.http import HttpResponse
from django.shortcuts import get_object_or_404, redirect
from django.urls import reverse

from analyzer.models import Task
from analyzer.utils import staff_check


@login_required
@user_passes_test(staff_check)
def delete_task(request, task_id: int) -> HttpResponse:
    """Delete specified task. Redirect to the list from which the task came."""

    if request.method == "POST":
        task = get_object_or_404(Task, pk=task_id)

        redir_url = reverse("analyzer:list_detail",
                            kwargs={"list_id": task.task_list.id, "list_slug": task.task_list.slug}, )

        # Permissions
        if not (request.user.is_superuser or (task.assigned_to == request.user)
                or (task.task_list.group in request.user.groups.all())):
            raise PermissionDenied

        task.delete()

        messages.success(request, "Task from '{}' has been deleted".format(task.username))
        return redirect(redir_url)

    else:
        raise PermissionDenied

analyzer/views/import_csv.py
from django.contrib import messages
from django.contrib.auth.decorators import login_required, user_passes_test
from django.http import HttpResponse
from django.shortcuts import redirect, render, reverse

from analyzer.operations.csv_importer import CSVImporter
from analyzer.utils import staff_check


@login_required
@user_passes_test(staff_check)
def import_csv(request) -> HttpResponse:
    """Import a specifically formatted CSV into stored tasks."""

    ctx = {"results": None}

    if request.method == "POST":
        filepath = request.FILES.get("csvfile")

        if not filepath:
            messages.error(request, "You must supply a CSV file to import.")
            return redirect(reverse("analyzer:import_csv"))

        importer = CSVImporter()
        results = importer.upsert(filepath)

        if results:
            ctx["results"] = results
        else:
            messages.error(request, "Could not parse provided CSV file.")
            return redirect(reverse("analyzer:import_csv"))

    return render(request, "analyzer/import_csv.html", context=ctx)

analyzer/views/list_detail.py
import bleach
from django.contrib import messages
from django.core.exceptions import ValidationError
from django.utils.safestring import mark_safe
from django.http import HttpResponse
from django.core.validators import validate_email
from django.shortcuts import get_object_or_404, redirect, render

from analyzer.forms import AddEditTaskForm
from analyzer.models import Task, TaskList


def list_detail(request, list_id=None, list_slug=None, view_checked=False) -> HttpResponse:
    """Display and manage tasks in a list."""

    # Defaults
    task_list = None
    form = None

    # Which tasks to show on this list view?
    if list_slug == "mine":
        tasks = Task.objects.filter(assigned_to=request.user)

    else:
        # Show a specific list, ensuring permissions.
        task_list = get_object_or_404(TaskList, id=list_id)
        tasks = Task.objects.filter(task_list=task_list.id)

    # Additional filtering
    if view_checked:
        tasks = tasks.filter(checked=True)
    else:
        tasks = tasks.filter(checked=False)

    # ######################
    #  Add New Task Form
    # ######################

    if request.POST.getlist("add_edit_task"):
        form = AddEditTaskForm(request.user, request.POST,
                               initial={"assigned_to": request.user.id, "priority": 999, "task_list": task_list}, )

        if form.is_valid():
            new_task = form.save(commit=False)
            new_task.created_by = bleach.clean(form.cleaned_data["username"], strip=True)
            new_task.note = bleach.clean(form.cleaned_data["note"], strip=True)

            try:
                validate_email(new_task.email)

                form.save()

                messages.success(request, 'New task from {t} has been added!'.format(t=new_task.username))
                messages.info(request, mark_safe('You can add your attachments here: '
                                                 '<a href="../../task/' + new_task.id + '">' + new_task.id + '</a>.'))

                return redirect(request.path)
            except ValidationError:
                messages.error(request, 'Enter correct email!')
    else:
        # Don't allow adding new tasks on some views
        if list_slug not in ["mine", "recent-add", "recent-complete"]:
            form = AddEditTaskForm(request.user,
                                   initial={"assigned_to": request.user.id, "priority": 999, "task_list": task_list}, )

    context = {
        "list_id": list_id,
        "list_slug": list_slug,
        "task_list": task_list,
        "form": form,
        "tasks": tasks,
        "view_checked": view_checked,
    }

    return render(request, "analyzer/list_detail.html", context)

analyzer/templates/analyzer/add_list.html
{% extends "analyzer/base.html" %}
{% block page_heading %}{% endblock %}
{% block title %}Add List{% endblock %}

{% block content %}
    <div class="content-section-main-title" style="margin-bottom: 14px; font-size: 20px;">Add a list</div>

    <form action="" method="post">
    {% csrf_token %}
        <div class="form-group">
            <label for="id_name">List Name</label>
            <input type="text" class="form-control" id="id_name" name="name" aria-describedby="inputNameHelp" placeholder="">
            <small id="inputNameHelp" class="form-text text-muted">The full display name for this list.</small>
        </div>

        <div class="form-group">
            <label for="id_group">Group</label>
            {{ form.group }}
        </div>

        <div style="text-align:center;">
            <button type="submit" class="btn btn-primary" style="width: 200px;">Submit</button>
        </div>
    </form>
{% endblock %}

analyzer/templates/analyzer/list_lists.html
{% extends "analyzer/base.html" %}
{% block title %}{{ list_title }} Task Lists{% endblock %}

{% block content %}
    <div class="content-section-main-title">Tasks Lists ({{ task_count }} tasks in {{ list_count }} list{{ list_count|pluralize }})</div>

    {% regroup lists by group as section_list %}
    {% for group in section_list %}
        <div class="content-section-title">Group: {{ group.grouper }}</div>
        <ul>
            {% for task in group.list %}
                <li class="all-products" onclick="window.location.href='{% url "analyzer:list_detail" task.id task.slug %}';">
                    <div class="products">
                        <a href="{% url 'analyzer:list_detail' task.id task.slug %}" style="color: var(--theme-color);">{{ task.name }}</a>
                    </div>

                    <span class="status">
                        {% if task.task_set.count > 0 %}
                            <span class="status-circle green"></span>Updated
                        {% else %}
                            <span class="status-circle"></span>Not Updated Yet
                        {% endif %}
                    </span>

                    <div class="button-wrapper-main" style="padding-top: 0; margin-left: 40px;">
                        <button class="content-button status-button open" onclick="location.href='{% url "analyzer:list_detail" task.id task.slug %}';" >Open</button>
                        <span class="badge badge-primary badge-pill" style="margin-left: 20px;">{{ task.task_set.count }}</span>
                    </div>
                </li>
            {% endfor %}
        </ul>
    {% endfor %}

    <div class="button-wrapper-main">
        {% if user.is_staff %}
            <a href="{% url 'analyzer:add_list' %}" class="btn btn-primary">Create new task list</a>
        {% else %}
            <a href="" class="btn btn-primary disabled">If you were staff, you could create a new list</a>
        {% endif %}
    </div>
{% endblock %}

analyzer/templates/analyzer/task_detail.html
{% extends "analyzer/base.html" %}
{% block title %}Task:{{ task.username }}{% endblock %}

{% block extrahead %}
    {{ form.media }}
    {{ merge_form.media }}
{% endblock %}

{% block content %}
    <div class="card-deck">
        <div class="item col-sm-7" style="cursor: default;">
            <div class="card-body">
                <div class="content-section-main-title" style="font-size: 20px;">{{ task.username }}</div>
                {% if task.note %}
                    <div class="content-section-title" style="margin: 0;">{{ task.note|safe|urlize|linebreaks }}</div>
                {% endif %}
            </div>
        </div>

        <div class="col-sm-4 p-0">
            <ul>
                {% if user.is_authenticated %}
                <li>
                    <button class="btn btn-sm btn-primary" id="EditTaskButton" type="button"
                            data-toggle="collapse" data-target="#TaskEdit">
                        Edit Task
                    </button>

                    <form method="post" action="{% url "analyzer:task_toggle_done" task.id %}" role="form" class="d-inline">
                        {% csrf_token %}
                        <div style="display:inline; text-align: center;">
                            <button class="btn btn-sm btn-info" type="submit" name="toggle_done" style="width: auto; margin: 0 10px 0 0; font-size: 14px;">
                                {% if task.checked %} Mark Not Done {% else %} Mark Done {% endif %}
                            </button>
                        </div>
                    </form>

                    <form method="post" action="{% url "analyzer:delete_task" task.id %}" role="form" class="d-inline">
                        {% csrf_token %}
                        <div style=" display: block; text-align: center;">
                            <button class="btn btn-sm btn-danger" type="submit" name="submit_delete" style="width: auto; margin: 0; font-size: 14px;">
                                Delete
                            </button>
                        </div>
                    </form>
                </li>
                {% endif %}

                <li>
                    <strong>Assigned to: &nbsp;</strong>
                    {% if task.assigned_to %}{{ task.assigned_to }}{% else %}Anyone{% endif %}
                </li>

                <li>
                    <strong>Reported by: &nbsp;</strong> {{ task.username }}
                </li>

                <li>
                    <strong>Email: &nbsp;</strong> {{ task.email }}
                </li>

                {% if task.checked %}
                    <li>
                        <strong>Checked on: &nbsp;</strong> {{ task.checked_date}}
                    </li>
                {% else %}
                    <li>
                        <strong>Checked: &nbsp;</strong> {{ task.checked|yesno:"Yes,No" }}
                    </li>
                {% endif %}

                <li>
                    <strong>In list: &nbsp;</strong>
                    <a href="{% url 'analyzer:list_detail' task.task_list.id task.task_list.slug %}" style="color: #1496bb; text-decoration: none;">
                        {{ task.task_list }}
                    </a>
                </li>
            </ul>
        </div>
    </div>

    <div id="TaskEdit" class="collapse">
        {# Task edit / new task form #}
        {% include 'analyzer/include/task_edit.html' %}
        {% if merge_form is not None %}
            <form action="" method="post">
                <div class="card border-danger" style="margin-top: 30px;">
                    <div class="item-text" style="color: var(--theme-color); font-size: 18px;">Merge task</div>
                    <div class="card-body">
                        <div class="">
                            <p style="color: var(--theme-color);">Merging is a destructive operation. This task will not exist anymore, and comments will be moved to the target task.</p>
                            {% csrf_token %}
                            {% for field in merge_form.visible_fields %}
                                <p>
                                    {{ field.errors }}
                                    {{ field }}
                                </p>
                            {% endfor %}
                            <input class="d-inline btn btn-sm btn-outline-danger" style="font-size: 16px;" type="submit" name="merge_task_into" value=" Merge ">
                        </div>
                    </div>
                </div>
            </form>
        {% endif %}
    </div>

    {% if attachments_enabled %}
        <div class="card mt-4">
            <div class="item-text" style="color: var(--theme-color);">Attachments</div>

            <div class="card-body pb-0">
                {% if task.attachment_set.count %}
                    <div class="table-responsive">
                        <table class="table mb-3">
                            <thead>
                            <tr style="color: var(--table-text); background: var(--table-bg);">
                                <th>File</th>
                                <th>Uploaded</th>
                                <th>Type</th>
                                {% if user.is_authenticated %}
                                <th>Analyze</th>
                                {% endif %}
                                <th>Remove</th>
                            </tr>
                            </thead>

                            <tbody>
                            {% for attachment in task.attachment_set.all %}
                                <tr style="color: var(--content-title-color);">
                                    <td><a style="color: #1496bb;" href="{{ attachment.file.url }}">{{ attachment.filename }}</a></td>
                                    <td>{{ attachment.timestamp }}</td>
                                    <td>{{ attachment.extension.lower }}</td>
                                    {% if user.is_authenticated %}
                                    <td>
                                        <form action="{% url "analyzer:prediction" attachment.id %}" method="POST">
                                            {% csrf_token %}
                                            <button type="submit" class="btn btn-success btn-sm" style="width: 50px;">
                                                <i class="fa fa-play"></i>
                                            </button>
                                        </form>
                                    </td>
                                    {% endif %}
                                    <td>
                                        <form action="{% url "analyzer:remove_attachment" attachment.id %}" method="POST">
                                            {% csrf_token %}
                                            <input type="submit" value="X" class="btn btn-danger btn-sm" style="width: 50px;">
                                        </form>
                                    </td>
                                </tr>
                            {% endfor %}
                            </tbody>
                        </table>
                    </div>
                {% endif %}

                <form method="POST" action="" enctype="multipart/form-data" style="width:50%;">
                    {% csrf_token %}
                    <div class="input-group mb-3">
                        <div class="custom-file">
                            <input type="file" class="custom-file-input" accept="application/pdf" id="attachment_file_input" name="attachment_file_input" />
                            <label class="custom-file-label" for="attachment_file_input">Choose file</label>
                        </div>

                        <div class="input-group-append">
                            <button class="btn btn-primary" style="font-size: 16px;">Upload</button>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    {% endif %}

    {% if user.is_authenticated %}
    <div class="mt-3" style="margin: 0 20px 0 20px;">
        <div class="content-section-title" style="font-size: 20px; text-align: center; color: var(--theme-color);">Add comment</div>
        <form action="" method="post">
            {% csrf_token %}
            <div class="form-group">
                <textarea class="form-control" name="comment-body" rows="3" required></textarea>
            </div>
            <input class="btn btn-sm btn-primary" type="submit" name="add_comment" value="Add Comment" style="font-size: 16px;">
        </form>
    </div>
    {% endif %}

    <div class="task_comments mt-4">
        {% if comment_list %}
            <div class="content-section-title" style="font-size: 20px; color: var(--theme-color); text-align: center;">Comments on this task</div>
            {% for comment in comment_list %}
                <div class="mb-3 card">
                    <div class="item-text" style="color: var(--theme-color); font-size: 16px;">
                        <div class="float-left" style="margin-left: 10px;">
                            {{ comment.author_text }}
                        </div>

                        <span class="float-right d-inline-block" style="color: var(--content-title-color);">
                            {{ comment.date|date:"F d Y P" }}
                        </span>
                    </div>

                    <div class="{{ comment_classes | join:" " }} card-body" style="color: var(--content-title-color);">
                        {{ comment.body|safe|urlize|linebreaks }}
                    </div>
                </div>
            {% endfor %}
        {% else %}
            <div class="content-section-main-title" style="font-size: 20px;">No comments (yet)</div>
        {% endif %}
    </div>
{% endblock %}

{% block extra_js %}
    {# Support file attachment uploader #}
    <script>
        $('#attachment_file_input').on('change',function(){
            let fileName = $(this).val().replace('C:\\fakepath\\', " ");
            $(this).next('.custom-file-label').html(fileName);
        })
    </script>
{% endblock extra_js %}